# -*- coding: utf-8 -*-
"""ConversaodeVideo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1edq7M1X2x_tXSh4x9Zt2iU_WOSN5wyXU
"""

import subprocess

infile = 'onde está'
outfile = 'onde a conversão vai estar'

subprocess.run(['ffmpeg', '-i', infile, outfile])